### ISSUE TITLE
todos to make jupyterlite/xeus the default (ie steps to deprectate jupyterlite/xeus-<lang>-kernels

### ISSUE THREAD

**Issue by DerThorsten** [jupyterlite/xeus#13]
What is needed to replace  jupyterlite/xeus-<lang>-kernels (in particular [ jupyterlite/xeus-python-kernel](https://github.com/jupyterlite/xeus-python-kernel)):
   * [x] at least some documentation on how to use this (https://github.com/jupyterlite/xeus/issues/8)
       * [x] usage with kernels installed from emscripten-forge
       * [x] usage with kernels installed from local PREFIX
       * [x] usage with additional directories mounted
   * [ ] expose empack filtering configuration as a parameter (like xeus-python-kernel) (https://github.com/jupyterlite/xeus/issues/12)
   * [ ] make tests pass https://github.com/jupyterlite/xeus/issues/14
   * [ ] add / port tests  jupyterlite/xeus-python-kernel (https://github.com/jupyterlite/xeus/issues/7)
   * [x] release on PyPI / release on conda-forge (does this need to be also on npm?) (https://github.com/jupyterlite/xeus/issues/15)

Probably needed:
  * [ ] documentation on readthedocs #17

**Comment by martinRenou** [comment]
Closing as this is already split in multiple issues here, under the milestone 0.1.0 https://github.com/jupyterlite/xeus/milestone/1
